/** Original banquet templates. Existing template ids and visual settings are preserved. */
export const templates = [
  { id: 'wedding-rose', category: '婚礼婚庆', name: '玫瑰誓约', description: '柔粉花枝 · 浪漫婚礼',
    bg: '#f5e8e3', ink: '#743d50', accent: '#aa6978', kicker: 'THE WEDDING', title: '我们结婚啦',
    subtitle: '林先生 & 陈小姐', detail: '2026.10.18  ·  幸福礼堂', footer: '以爱之名，共赴余生', art: 'flowers', layout: 'classic' },
  { id: 'wedding-red', category: '婚礼婚庆', name: '囍结良缘', description: '朱红描金 · 中式婚礼',
    bg: '#8e202c', ink: '#ffe2a2', accent: '#d9af64', kicker: '良辰美景 · 天作之合', title: '囍结良缘',
    subtitle: '林先生 & 陈小姐', detail: '2026.10.18  ·  婚礼盛典', footer: '承蒙厚爱，诚邀见证', art: 'rings', layout: 'classic' },
  { id: 'wedding-garden', category: '婚礼婚庆', name: '回门归宁宴', description: '鼠尾草绿 · 回门归宁宴',
    bg: '#e4ece0', ink: '#355b43', accent: '#839765', kicker: '新婚归宁 · 喜聚娘家', title: '回门归宁',
    subtitle: '回门归宁宴 · 恭迎亲友', detail: '2026.10.18 · 宴会厅', footer: '感谢家人厚爱，今日欢喜团圆', art: 'leaves', layout: 'arch' },
  { id: 'wedding-peony', category: '婚礼婚庆', name: '牡丹良缘', description: '绛紫牡丹 · 华美喜宴',
    bg: '#4e2942', ink: '#f8e2ba', accent: '#c89891', kicker: '花开并蒂 · 喜结同心', title: '花好月圆',
    subtitle: '新婚庆典 · 恭迎亲友', detail: '良辰吉日 · 婚宴厅', footer: '一席喜宴，满堂祝福', art: 'peony', layout: 'seal' },
  { id: 'wedding-ivory', category: '婚礼婚庆', name: '银婚纪念', description: '象牙白金 · 25年银婚纪念',
    bg: '#f5f0e6', ink: '#645342', accent: '#b49970', kicker: '相伴二十五载 · 初心仍如故', title: '银婚之喜',
    subtitle: '结婚25周年纪念宴 · 家人同庆', detail: '2026.10.18 · 宴会厅', footer: '二十五年相守，把日常过成珍贵回忆', art: 'rings', layout: 'ribbon' },
  { id: 'wedding-lantern', category: '婚礼婚庆', name: '喜灯迎客', description: '正红喜灯 · 热闹婚宴',
    bg: '#b52e24', ink: '#fff0cf', accent: '#f1bd61', kicker: '良缘天定 · 喜宴相迎', title: '喜迎亲朋',
    subtitle: '新婚答谢宴', detail: '2026.10.18 · 喜宴厅', footer: '感谢厚爱，敬请入席', art: 'lanterns', layout: 'banner' },
  { id: 'wedding-engagement', category: '婚礼婚庆', name: '团扇定情', description: '暖杏团扇 · 雅致订婚',
    bg: '#f2dec7', ink: '#7a3d35', accent: '#bd8460', kicker: '两姓联姻 · 一堂缔约', title: '订婚之喜',
    subtitle: '佳偶相约 · 亲友同庆', detail: '良辰吉日 · 宴会厅', footer: '承蒙见证，喜乐长安', art: 'fan', layout: 'seal' },
  { id: 'wedding-cloud', category: '婚礼婚庆', name: '金婚庆典', description: '暖金祥云 · 50年金婚庆典',
    bg: '#6e4926', ink: '#ffe9a9', accent: '#d3ac60', kicker: '风雨五十载 · 相伴到如今', title: '金婚之喜',
    subtitle: '结婚50周年纪念宴 · 阖家同庆', detail: '2026.10.18 · 宴会厅', footer: '半世纪携手同行，愿往后岁月安康常乐', art: 'clouds', layout: 'arch' },

  { id: 'graduation', category: '升学谢师', name: '星辰远航', description: '深蓝星光 · 毕业纪念',
    bg: '#202c55', ink: '#f8efd9', accent: '#d8bf84', kicker: 'THE NEXT CHAPTER', title: '前程似锦',
    subtitle: '2026 届毕业典礼', detail: '青春不散场  ·  梦想正启航', footer: '愿此去繁花似锦，再相逢依然如故', art: 'stars', layout: 'classic' },
  { id: 'study-admission', category: '升学谢师', name: '金榜题名', description: '朱砂书卷 · 升学喜宴',
    bg: '#a52f32', ink: '#fff0ca', accent: '#e3ba6e', kicker: '寒窗有获 · 金榜传喜', title: '金榜题名',
    subtitle: '升学答谢宴 · 恭迎亲友', detail: '2026.10.18 · 宴会厅', footer: '感谢一路关怀，共贺锦绣前程', art: 'scroll', layout: 'banner' },
  { id: 'study-laurel', category: '升学谢师', name: '折桂之喜', description: '松绿桂冠 · 雅致升学',
    bg: '#224b43', ink: '#f8edca', accent: '#d3bd78', kicker: '勤学笃行 · 喜报新章', title: '蟾宫折桂',
    subtitle: '升学庆贺 · 感恩相聚', detail: '2026.10.18 · 喜宴厅', footer: '带着大家的祝福，向更远处出发', art: 'laurel', layout: 'seal' },
  { id: 'study-teacher', category: '升学谢师', name: '桃李谢恩', description: '米白青荷 · 温润谢师',
    bg: '#f0ead9', ink: '#496054', accent: '#a79068', kicker: '春风化雨 · 桃李芬芳', title: '师恩难忘',
    subtitle: '谢师宴 · 敬献恩师', detail: '2026.10.18 · 宴会厅', footer: '一席感恩，敬谢谆谆教诲', art: 'lotus', layout: 'arch' },
  { id: 'study-campus', category: '升学谢师', name: '青春礼成', description: '晴空蓝帽 · 毕业庆贺',
    bg: '#e2edf4', ink: '#304d74', accent: '#c49a5f', kicker: '青春作序 · 毕业启程', title: '毕业快乐',
    subtitle: '毕业纪念宴 · 同窗共庆', detail: '2026.10.18 · 宴会厅', footer: '珍藏同窗时光，奔赴各自热爱', art: 'cap', layout: 'ribbon' },
  { id: 'study-future', category: '升学谢师', name: '青云有路', description: '墨蓝流云 · 励志启程',
    bg: '#253d51', ink: '#f5e7c9', accent: '#8fb8c0', kicker: '学有所成 · 志在远方', title: '青云直上',
    subtitle: '学业有成 · 亲友同贺', detail: '良辰吉日 · 宴会厅', footer: '愿脚下有路，心中有光', art: 'clouds', layout: 'banner' },

  { id: 'birthday', category: '生日寿宴', name: '彩色心愿', description: '轻盈气球 · 生日派对',
    bg: '#e8eff5', ink: '#315b77', accent: '#dfac61', kicker: 'MAKE A WISH', title: '生日快乐',
    subtitle: '愿每一岁，都奔赴热爱', detail: '2026.10.18  ·  生日派对', footer: '把美好的愿望，写进今天', art: 'balloons', layout: 'classic' },
  { id: 'birthday-longevity', category: '生日寿宴', name: '花甲寿宴', description: '枣红牡丹 · 六十花甲寿宴',
    bg: '#792b2c', ink: '#ffe2a4', accent: '#cc9a59', kicker: '六十华诞 · 福寿绵长', title: '花甲寿喜',
    subtitle: '花甲寿宴 · 亲友同贺', detail: '良辰吉日 · 寿宴厅', footer: '愿您岁岁安康，笑口常开', art: 'peony', layout: 'seal' },
  { id: 'birthday-peace', category: '生日寿宴', name: '古稀寿宴', description: '浅青荷影 · 七十古稀寿宴',
    bg: '#dfece6', ink: '#375b50', accent: '#a79563', kicker: '七十华诞 · 岁月生香', title: '古稀寿庆',
    subtitle: '古稀寿宴 · 温暖相聚', detail: '2026.10.18 · 寿宴厅', footer: '愿您身体康健，日日舒心，笑意常在', art: 'lotus', layout: 'classic' },
  { id: 'birthday-cake', category: '生日寿宴', name: '儿童生日', description: '奶油粉橙 · 儿童生日派对',
    bg: '#f8e7d4', ink: '#86513d', accent: '#d58b7c', kicker: '童年有甜 · 成长有爱', title: '儿童生日快乐',
    subtitle: '儿童生日宴 · 家人同庆', detail: '2026.10.18 · 派对宴会厅', footer: '一起吹蜡烛，愿你健康快乐地长大', art: 'cake', layout: 'ribbon' },
  { id: 'birthday-starlight', category: '生日寿宴', name: '十八岁成人礼', description: '午夜紫金 · 十八岁成人礼',
    bg: '#352b52', ink: '#fbebd2', accent: '#c6a7d7', kicker: '青春礼成 · 勇敢启程', title: '十八岁成人礼',
    subtitle: '18岁生日宴 · 礼成启程', detail: '2026.10.18 · 宴会厅', footer: '愿你心有热爱，肩有担当，脚步坚定', art: 'stars', layout: 'arch' },
  { id: 'birthday-golden', category: '生日寿宴', name: '八十大寿', description: '暖金桂冠 · 八十大寿庆典',
    bg: '#5d4531', ink: '#fff0c5', accent: '#d3ae67', kicker: '八十华诞 · 福泽绵长', title: '八十大寿',
    subtitle: '八十大寿宴 · 阖家同庆', detail: '良辰吉日 · 寿宴厅', footer: '敬祝您福寿安康，尽享天伦之乐', art: 'laurel', layout: 'banner' },

  { id: 'baby-fullmoon', category: '宝宝成长', name: '月满童心', description: '奶黄圆月 · 温柔满月',
    bg: '#f8efda', ink: '#76603e', accent: '#cfb879', kicker: '月满添喜 · 小小欢颜', title: '满月之喜',
    subtitle: '宝宝满月宴 · 诚邀亲友', detail: '2026.10.18 · 宴会厅', footer: '愿你健康长大，被爱轻轻包围', art: 'moon', layout: 'arch' },
  { id: 'baby-hundred', category: '宝宝成长', name: '百日小愿', description: '雾粉玩具 · 童真百日',
    bg: '#f3e3e6', ink: '#805263', accent: '#ba91a0', kicker: '百日欢喜 · 成长可期', title: '百日快乐',
    subtitle: '宝宝百日宴 · 欢迎莅临', detail: '2026.10.18 · 宝宝宴会厅', footer: '每一次微笑，都是家里的好天气', art: 'toys', layout: 'ribbon' },
  { id: 'baby-firstyear', category: '宝宝成长', name: '周岁抓周宴', description: '浅杏蛋糕 · 周岁抓周喜宴',
    bg: '#f4e3c7', ink: '#7d5433', accent: '#ce9454', kicker: '周岁礼成 · 新欢喜', title: '周岁抓周',
    subtitle: '周岁抓周宴 · 亲友同乐', detail: '2026.10.18 · 宴会厅', footer: '愿你所遇皆暖，所行皆坦途', art: 'cake', layout: 'banner' },
  { id: 'baby-arrival', category: '宝宝成长', name: '云朵报喜', description: '天蓝云朵 · 新生喜讯',
    bg: '#deedf4', ink: '#3f667c', accent: '#94b8c9', kicker: '新生命 · 新欢喜', title: '添丁之喜',
    subtitle: '新生庆贺 · 恭迎亲友', detail: '良辰吉日 · 宴会厅', footer: '谢谢你们，共享这份初见的喜悦', art: 'clouds', layout: 'classic' },
  { id: 'baby-growth', category: '宝宝成长', name: '童趣印记', description: '嫩绿积木 · 成长纪念',
    bg: '#e5edcc', ink: '#52643a', accent: '#a7b765', kicker: '童心闪亮 · 快乐生长', title: '快乐长大',
    subtitle: '成长纪念宴 · 一起欢聚', detail: '2026.10.18 · 宴会厅', footer: '愿好奇不减，愿笑容常在', art: 'toys', layout: 'seal' },
  { id: 'baby-balloons', category: '宝宝成长', name: '周岁生日', description: '湖蓝气球 · 宝宝周岁生日',
    bg: '#dceeed', ink: '#3c686a', accent: '#d1a56f', kicker: '一岁一礼 · 满心欢喜', title: '周岁生日快乐',
    subtitle: '宝宝周岁生日宴 · 欢迎入席', detail: '2026.10.18 · 亲子宴会厅', footer: '把第一个生日的快乐，收藏进成长相册', art: 'balloons', layout: 'ribbon' },

  { id: 'family-reunion', category: '家庭团聚', name: '团圆一席', description: '暖棕餐桌 · 温馨家宴',
    bg: '#efdfca', ink: '#654b37', accent: '#b48c5d', kicker: '一桌好菜 · 一家团圆', title: '团圆家宴',
    subtitle: '阖家欢聚 · 共话家常', detail: '2026.10.18 · 宴会厅', footer: '人间好滋味，最是团圆时', art: 'table', layout: 'classic' },
  { id: 'family-parents', category: '家庭团聚', name: '寸草春晖', description: '暖粉花枝 · 感恩双亲',
    bg: '#f0e1db', ink: '#785045', accent: '#bc8c7e', kicker: '养育之恩 · 常记心间', title: '感恩双亲',
    subtitle: '感恩家宴 · 温情相聚', detail: '2026.10.18 · 宴会厅', footer: '陪伴是最好的礼物，愿您健康常乐', art: 'flowers', layout: 'ribbon' },
  { id: 'family-anniversary', category: '家庭团聚', name: '相伴如初', description: '酒红双环 · 婚姻纪念',
    bg: '#632f3b', ink: '#f7e3c7', accent: '#c59770', kicker: '岁月为证 · 相爱如初', title: '相伴有你',
    subtitle: '结婚纪念宴 · 家人同庆', detail: '2026.10.18 · 宴会厅', footer: '一路相守，把平凡日子过成珍贵回忆', art: 'rings', layout: 'arch' },
  { id: 'family-gathering', category: '家庭团聚', name: '家风雅集', description: '竹青书卷 · 家族欢聚',
    bg: '#dfe5d3', ink: '#46583d', accent: '#a59561', kicker: '家人相聚 · 情谊相承', title: '亲情满堂',
    subtitle: '家族团聚宴 · 恭迎亲友', detail: '良辰吉日 · 宴会厅', footer: '围坐一堂，珍惜每一次相聚', art: 'scroll', layout: 'seal' },
  { id: 'family-homecoming', category: '家庭团聚', name: '归乡灯暖', description: '赭红灯火 · 归乡接风',
    bg: '#9b4431', ink: '#ffedcf', accent: '#e0b66c', kicker: '一路辛苦 · 欢迎回家', title: '归来是欢喜',
    subtitle: '接风家宴 · 亲友相聚', detail: '2026.10.18 · 宴会厅', footer: '家里的饭香，一直在等你', art: 'lanterns', layout: 'banner' },
  { id: 'family-farewell', category: '家庭团聚', name: '清风寄语', description: '水青团扇 · 温暖送行',
    bg: '#dce9e4', ink: '#45665a', accent: '#96a77e', kicker: '此去顺遂 · 常念归期', title: '家人的祝福',
    subtitle: '送行家宴 · 温暖相伴', detail: '2026.10.18 · 宴会厅', footer: '无论走到哪里，家都在你身后', art: 'fan', layout: 'arch' },

  { id: 'reunion-classmates', category: '同学战友', name: '同窗旧时光', description: '牛皮纸卷 · 怀旧同学会',
    bg: '#e9d7b7', ink: '#655039', accent: '#a8824b', kicker: '同窗一程 · 情谊一生', title: '同学，好久不见',
    subtitle: '同学联谊宴 · 共忆青春', detail: '2026.10.18 · 宴会厅', footer: '把分别后的故事，慢慢讲给彼此听', art: 'scroll', layout: 'ribbon' },
  { id: 'reunion-comrades', category: '同学战友', name: '岁月军情', description: '军绿桂冠 · 战友情深',
    bg: '#374735', ink: '#f4e5b8', accent: '#b9a363', kicker: '并肩岁月 · 铭记于心', title: '战友重逢',
    subtitle: '战友联谊宴 · 再叙情谊', detail: '2026.10.18 · 宴会厅', footer: '一声战友，一生牵挂', art: 'laurel', layout: 'banner' },
  { id: 'reunion-alumni', category: '同学战友', name: '校友华章', description: '藏蓝学士帽 · 校友雅聚',
    bg: '#293f60', ink: '#f4e7c8', accent: '#c0a779', kicker: '同出一校 · 共赴新章', title: '校友欢聚',
    subtitle: '校友联谊宴 · 欢迎莅临', detail: '2026.10.18 · 宴会厅', footer: '聊聊校园往事，也聊聊今天的自己', art: 'cap', layout: 'seal' },
  { id: 'reunion-friends', category: '同学战友', name: '老友围坐', description: '暖橘餐桌 · 轻松叙旧',
    bg: '#f3dec5', ink: '#7b5138', accent: '#c3945d', kicker: '老友如初 · 相聚有味', title: '老友见面',
    subtitle: '好友相聚 · 共叙近况', detail: '2026.10.18 · 宴会厅', footer: '好久不见，今天慢慢聊', art: 'table', layout: 'arch' },

  { id: 'celebration', category: '商务庆典', name: '鎏金盛典', description: '黑金光环 · 年会庆典',
    bg: '#17272b', ink: '#f4dfa9', accent: '#c5a36a', kicker: 'A NIGHT TO REMEMBER', title: '共赴新程',
    subtitle: '2026 年度盛典', detail: '10月18日 19:00  ·  宴会厅', footer: '感谢同行，让每一份努力闪耀', art: 'orbit', layout: 'classic' },
  { id: 'business-opening', category: '商务庆典', name: '启幕大吉', description: '正红帷幕 · 开业庆贺',
    bg: '#a12829', ink: '#ffe6b2', accent: '#d7ad62', kicker: '盛大启幕 · 嘉宾云集', title: '开业大吉',
    subtitle: '开业庆典答谢宴', detail: '2026.10.18 · 宴会厅', footer: '感谢莅临，与您共启新篇', art: 'curtain', layout: 'banner' },
  { id: 'business-thanks', category: '商务庆典', name: '诚意相邀', description: '深青绿叶 · 客户答谢',
    bg: '#224a4b', ink: '#e8edcf', accent: '#b2bd8a', kicker: '一路相伴 · 心怀感恩', title: '感谢有您',
    subtitle: '客户答谢宴 · 恭迎嘉宾', detail: '2026.10.18 · 宴会厅', footer: '以诚相待，携手前行', art: 'leaves', layout: 'arch' },
  { id: 'business-partnership', category: '商务庆典', name: '签约答谢宴', description: '钴蓝光环 · 合作签约答谢',
    bg: '#213b6a', ink: '#edf3ff', accent: '#8eaecf', kicker: '签约携手 · 共赴新程', title: '签约答谢',
    subtitle: '签约答谢晚宴 · 恭迎合作伙伴', detail: '2026.10.18 · 宴会厅', footer: '感谢信任与支持，期待携手创造新成果', art: 'orbit', layout: 'seal' },
  { id: 'business-awards', category: '商务庆典', name: '荣耀加冕', description: '墨紫桂冠 · 表彰晚宴',
    bg: '#352b3f', ink: '#ffedbe', accent: '#c8a05f', kicker: '致敬付出 · 见证荣光', title: '荣耀时刻',
    subtitle: '表彰庆功宴 · 欢迎莅临', detail: '2026.10.18 · 宴会厅', footer: '每一份认真，都值得被看见', art: 'laurel', layout: 'ribbon' },
  { id: 'business-launch', category: '商务庆典', name: '璀璨新程', description: '深海银蓝 · 新品庆典',
    bg: '#142f47', ink: '#e7f3fc', accent: '#8db9d1', kicker: '焕新出发 · 共见未来', title: '启航新篇',
    subtitle: '新品发布庆祝晚宴', detail: '2026.10.18 · 宴会厅', footer: '感谢见证，与您分享新成果', art: 'fireworks', layout: 'banner' },

  { id: 'welcome', category: '餐厅经营', name: '简约迎宾', description: '米白绿叶 · 活动欢迎',
    bg: '#edf0e8', ink: '#36524a', accent: '#93a489', kicker: 'WELCOME', title: '欢迎莅临',
    subtitle: '很高兴，在这里遇见你', detail: '2026.10.18  ·  活动现场', footer: '美好的相聚，从此刻开始', art: 'leaves', layout: 'classic' },
  { id: 'restaurant-menu', category: '餐厅经营', name: '时令上新', description: '米黄餐桌 · 当季菜品',
    bg: '#f1e6cb', ink: '#665237', accent: '#b69a58', kicker: '随时而食 · 用心入味', title: '时令新味',
    subtitle: '当季鲜味 · 诚邀品尝', detail: '今日供应 · 详情请咨询服务人员', footer: '认真做好每一道菜，温暖每一桌相聚', art: 'table', layout: 'banner' },
  { id: 'restaurant-banquet', category: '餐厅经营', name: '花厅喜宴', description: '豆沙花枝 · 宴会预订',
    bg: '#ebd7d4', ink: '#744846', accent: '#b17d72', kicker: '好日子 · 好宴席', title: '喜宴有约',
    subtitle: '婚宴 · 寿宴 · 家宴 · 聚会', detail: '宴会预订 · 欢迎到店咨询', footer: '从一席好菜开始，认真安排你的重要日子', art: 'flowers', layout: 'ribbon' },
  { id: 'restaurant-gathering', category: '餐厅经营', name: '周年店庆', description: '酱红灯笼 · 餐厅周年店庆',
    bg: '#77372d', ink: '#ffe4b0', accent: '#c69756', kicker: '周年同庆 · 感恩惠顾', title: '周年店庆',
    subtitle: '餐厅周年庆典 · 新老顾客同欢', detail: '2026.10.18 · 店庆宴会厅', footer: '感谢每一份信任，继续用好味道陪伴大家', art: 'lanterns', layout: 'seal' },

  { id: 'festival-spring', category: '传统节日', name: '新春团圆', description: '中国红灯 · 团年家宴',
    bg: '#a72924', ink: '#ffe6a9', accent: '#e5b357', kicker: '辞旧迎新 · 阖家团圆', title: '新春大吉',
    subtitle: '新春团圆宴 · 恭迎亲友', detail: '新春佳节 · 宴会厅', footer: '愿新的一年，家人安康，万事顺意', art: 'lanterns', layout: 'seal' },
  { id: 'festival-lantern', category: '传统节日', name: '元宵月圆', description: '夜蓝圆月 · 元宵欢聚',
    bg: '#2f3558', ink: '#f9e8bd', accent: '#dfaf6f', kicker: '月圆灯暖 · 人间团圆', title: '元宵喜乐',
    subtitle: '元宵家宴 · 共享好时光', detail: '元宵佳节 · 宴会厅', footer: '一碗汤圆，一桌团圆', art: 'moon', layout: 'arch' },
  { id: 'festival-dragonboat', category: '传统节日', name: '端午清和', description: '粽叶青荷 · 端午家宴',
    bg: '#dce6ce', ink: '#3f5a38', accent: '#a19a52', kicker: '粽香满席 · 端午安康', title: '端午安康',
    subtitle: '端午家宴 · 与家人相聚', detail: '端午佳节 · 宴会厅', footer: '愿家人无恙，愿日子清和', art: 'lotus', layout: 'ribbon' },
  { id: 'festival-midautumn', category: '传统节日', name: '月满中秋', description: '黛蓝金月 · 中秋团聚',
    bg: '#243d51', ink: '#f6e6bc', accent: '#c9ae71', kicker: '明月寄情 · 团圆此刻', title: '中秋团圆',
    subtitle: '中秋家宴 · 欢迎入席', detail: '中秋佳节 · 宴会厅', footer: '愿月圆人团圆，家和万事兴', art: 'moon', layout: 'classic' },
  { id: 'festival-national', category: '传统节日', name: '金秋欢聚', description: '暖红烟花 · 假日盛宴',
    bg: '#963629', ink: '#ffebbc', accent: '#deb56e', kicker: '金秋好时节 · 假日好相聚', title: '欢度国庆',
    subtitle: '国庆欢聚宴 · 恭迎嘉宾', detail: '国庆佳节 · 宴会厅', footer: '与亲友共享美味，把假日过得有滋有味', art: 'fireworks', layout: 'banner' },
  { id: 'festival-chongyang', category: '传统节日', name: '重阳敬老', description: '秋褐祥云 · 敬老家宴',
    bg: '#ebe0c6', ink: '#64523c', accent: '#b39b5f', kicker: '岁岁重阳 · 浓浓敬意', title: '九九安康',
    subtitle: '重阳敬老宴 · 温情相聚', detail: '重阳佳节 · 宴会厅', footer: '常陪长辈说说话，愿平安与笑容常在', art: 'clouds', layout: 'seal' },

  { id: 'party-neon', category: '主题派对', name: '霓光之夜', description: '墨蓝玫紫 · 轻快派对',
    bg: '#23213d', ink: '#f4defb', accent: '#bf83c7', kicker: '今晚相聚 · 快乐开场', title: '今晚尽兴',
    subtitle: '主题派对 · 好友同乐', detail: '2026.10.18 · 派对宴会厅', footer: '把烦恼暂放一旁，一起留下开心回忆', art: 'orbit', layout: 'banner' },
  { id: 'party-stage', category: '主题派对', name: '幕启好戏', description: '深紫帷幕 · 主题晚会',
    bg: '#442942', ink: '#fae6c8', accent: '#c79a79', kicker: '好戏登场 · 欢聚今宵', title: '今夜有戏',
    subtitle: '主题晚会 · 欢迎莅临', detail: '2026.10.18 · 宴会厅', footer: '掌声送给每一位认真准备的朋友', art: 'curtain', layout: 'arch' },
  { id: 'party-garden', category: '主题派对', name: '花间茶叙', description: '淡紫繁花 · 下午茶会',
    bg: '#e9e1ef', ink: '#685477', accent: '#b299c1', kicker: '花香茶暖 · 好友相伴', title: '花间小聚',
    subtitle: '主题茶会 · 欢迎入席', detail: '2026.10.18 · 花厅', footer: '喝杯茶，说说话，享受慢下来的时光', art: 'flowers', layout: 'ribbon' },
  { id: 'party-chinese', category: '主题派对', name: '国风雅宴', description: '青瓷折扇 · 国风主题',
    bg: '#dce7e3', ink: '#3f605a', accent: '#a39a71', kicker: '清风入席 · 雅趣相逢', title: '国风雅集',
    subtitle: '国风主题宴 · 恭迎知音', detail: '2026.10.18 · 雅宴厅', footer: '于一席美味中，细品相聚的风雅', art: 'fan', layout: 'seal' },

  { id: 'milestone-home', category: '人生喜事', name: '新居常暖', description: '浅苔绿叶 · 乔迁之喜',
    bg: '#e6ebda', ink: '#4b6043', accent: '#9ca66d', kicker: '新居新景 · 喜乐常在', title: '乔迁之喜',
    subtitle: '乔迁答谢宴 · 恭迎亲友', detail: '良辰吉日 · 宴会厅', footer: '感谢关怀，愿新家四季温暖', art: 'leaves', layout: 'arch' },
  { id: 'milestone-promotion', category: '人生喜事', name: '锦程可期', description: '赤陶书卷 · 晋升庆贺',
    bg: '#884639', ink: '#ffe8c7', accent: '#d4ab79', kicker: '耕耘有获 · 前路可期', title: '再启新程',
    subtitle: '晋升庆贺宴 · 感恩同行', detail: '2026.10.18 · 宴会厅', footer: '感谢一路支持，未来继续踏实前行', art: 'scroll', layout: 'ribbon' },
  { id: 'milestone-retirement', category: '人生喜事', name: '从容新篇', description: '晴灰流云 · 退休纪念',
    bg: '#e6e9e6', ink: '#485c59', accent: '#9caa91', kicker: '岁月有功 · 生活有趣', title: '自在新生活',
    subtitle: '荣休纪念宴 · 亲友同庆', detail: '2026.10.18 · 宴会厅', footer: '愿往后的时光，有闲情，也有新热爱', art: 'clouds', layout: 'classic' },
  { id: 'milestone-journey', category: '人生喜事', name: '追光远行', description: '深蓝金星 · 新程送祝',
    bg: '#23344c', ink: '#fae6bc', accent: '#c7ab72', kicker: '带着祝福 · 奔赴热爱', title: '一路生花',
    subtitle: '新程祝福宴 · 感谢相伴', detail: '2026.10.18 · 宴会厅', footer: '愿新的旅程，步步踏实，处处有光', art: 'stars', layout: 'classic' },
]

export const categories = [...new Set(templates.map(t => t.category))]
